/**
 * Configuración de las 25 capas para el efecto parallax
 *
 * EFECTO CÁMARA: invertX/invertY = true hace que el movimiento sea como una cámara
 * (mouse derecha → revela lado derecho)
 */

export const layersConfig = [
  // === CAPA 1: FONDO PRINCIPAL ===
  // Imagen 1771x865 → maxOffset ~130px para pantallas 16:9
  {
    id: 'layer-01',
    name: 'Fondo Principal',
    depth: 1,
    position: 'center',
    offsetX: 0,
    offsetY: 0,
    size: 'cover',
    zIndex: 1,
    invertX: true,
    invertY: false,
    maxOffset: 85,
    onlyHorizontal: true,
    loop: true,
  },

  // === ELEMENTOS FIJOS AL FONDO (se mueven igual que el background) ===
  {
    id: 'layer-02',
    name: 'Fan 1',
    depth: 1,
    position: 'topleft',
    offsetX: 160,
    offsetY: 101,
    size: 'sm',
    zIndex: 2,
    invertX: true,
    invertY: false,
    maxOffset: 85,
    onlyHorizontal: true,
    loop: true,
  },
  {
    id: 'layer-03',
    name: 'Fan 2',
    depth: 1,
    position: 'topCenter',
    offsetX: -260,
    offsetY: 125,
    size: 'sm',
    zIndex: 2,
    invertX: true,
    invertY: false,
    maxOffset: 85,
    onlyHorizontal: true,
    loop: true,
  },
  {
    id: 'layer-04',
    name: 'Fan 3',
    depth: 1,
    position: 'topCenter',
    offsetX: -80,
    offsetY: 150,
    size: 'sm',
    zIndex: 2,
    invertX: true,
    invertY: false,
    maxOffset: 85,
    onlyHorizontal: true,
    loop: true,
  },
  {
    id: 'layer-05',
    name: 'Fan 4',
    depth: 1,
    position: 'center',
    offsetX: 0,
    offsetY: 0,
    size: 'md',
    zIndex: 2,
    invertX: true,
    invertY: false,
    maxOffset: 85,
    onlyHorizontal: true,
    loop: true,
  },
  {
    id: 'layer-06',
    name: 'Fan 5',
    depth: 1,
    position: 'center',
    offsetX: 0,
    offsetY: 0,
    size: 'md',
    zIndex: 2,
    invertX: true,
    invertY: false,
    maxOffset: 85,
    onlyHorizontal: true,
    loop: true,
  },
  {
    id: 'layer-07',
    name: 'Speaker Left',
    depth: 1,
    position: 'center',
    offsetX: 0,
    offsetY: 0,
    size: 'md',
    zIndex: 2,
    invertX: true,
    invertY: false,
    maxOffset: 85,
    onlyHorizontal: true,
    loop: true,
  },
  {
    id: 'layer-08',
    name: 'Speaker Right',
    depth: 1,
    position: 'center',
    offsetX: 0,
    offsetY: 0,
    size: 'md',
    zIndex: 2,
    invertX: true,
    invertY: false,
    maxOffset: 85,
    onlyHorizontal: true,
    loop: true,
  },
  {
    id: 'layer-09',
    name: 'Main',
    depth: 1,
    position: 'center',
    offsetX: 0,
    offsetY: 0,
    size: 'lg',
    zIndex: 3,
    invertX: true,
    invertY: false,
    maxOffset: 85,
    onlyHorizontal: true,
    loop: true,
  },

  // === CAPAS INTERMEDIAS ===
  {
    id: 'layer-10',
    name: 'Elemento Medio 1',
    depth: 0.4,
    position: 'center',
    offsetX: -25,
    offsetY: -20,
    size: 'sm',
    zIndex: 5,
    invertX: true,
    invertY: true,
    maxOffset: 50,
    loop: true,
  },
  {
    id: 'layer-11',
    name: 'Elemento Medio 2',
    depth: 0.4,
    position: 'center',
    offsetX: 25,
    offsetY: 20,
    size: 'sm',
    zIndex: 5,
    invertX: true,
    invertY: true,
    maxOffset: 50,
    loop: true,
  },
  {
    id: 'layer-12',
    name: 'Elemento Medio Izquierda',
    depth: 0.45,
    position: 'centerLeft',
    offsetX: 20,
    offsetY: -15,
    size: 'sm',
    zIndex: 6,
    invertX: true,
    invertY: true,
    maxOffset: 55,
    loop: true,
  },
  {
    id: 'layer-13',
    name: 'Elemento Medio Derecha',
    depth: 0.45,
    position: 'centerRight',
    offsetX: -20,
    offsetY: 15,
    size: 'sm',
    zIndex: 6,
    invertX: true,
    invertY: true,
    maxOffset: 55,
    loop: true,
  },

  // === CAPAS CENTRALES (Protagonistas) ===
  {
    id: 'layer-14',
    name: 'Principal Izquierda',
    depth: 0.5,
    position: 'center',
    offsetX: -30,
    offsetY: 5,
    size: 'xl',
    zIndex: 10,
    invertX: true,
    invertY: true,
    maxOffset: 60,
    loop: true,
  },
  {
    id: 'layer-15',
    name: 'Principal Centro',
    depth: 0.5,
    position: 'center',
    offsetX: 0,
    offsetY: 0,
    size: '2xl',
    zIndex: 11,
    invertX: true,
    invertY: true,
    maxOffset: 60,
    loop: true,
  },
  {
    id: 'layer-16',
    name: 'Principal Derecha',
    depth: 0.5,
    position: 'center',
    offsetX: 30,
    offsetY: 5,
    size: 'xl',
    zIndex: 10,
    invertX: true,
    invertY: true,
    maxOffset: 60,
    loop: true,
  },

  // === CAPAS FRONTALES INTERMEDIAS ===
  {
    id: 'layer-17',
    name: 'Detalle Frontal 1',
    depth: 0.6,
    position: 'topLeft',
    offsetX: 20,
    offsetY: 25,
    size: 'sm',
    zIndex: 15,
    invertX: true,
    invertY: true,
    maxOffset: 65,
    loop: true,
  },
  {
    id: 'layer-18',
    name: 'Detalle Frontal 2',
    depth: 0.6,
    position: 'topRight',
    offsetX: -20,
    offsetY: 25,
    size: 'sm',
    zIndex: 15,
    invertX: true,
    invertY: true,
    maxOffset: 65,
    loop: true,
  },
  {
    id: 'layer-19',
    name: 'Detalle Frontal 3',
    depth: 0.65,
    position: 'bottomLeft',
    offsetX: 25,
    offsetY: -20,
    size: 'md',
    zIndex: 16,
    invertX: true,
    invertY: true,
    maxOffset: 70,
    loop: true,
  },
  {
    id: 'layer-20',
    name: 'Detalle Frontal 4',
    depth: 0.65,
    position: 'bottomRight',
    offsetX: -25,
    offsetY: -20,
    size: 'md',
    zIndex: 16,
    invertX: true,
    invertY: true,
    maxOffset: 70,
    loop: true,
  },

  // === CAPAS FRONTALES (Primer plano) ===
  {
    id: 'layer-21',
    name: 'Partícula 1',
    depth: 0.75,
    position: 'center',
    offsetX: -40,
    offsetY: -30,
    size: 'xs',
    zIndex: 20,
    invertX: true,
    invertY: true,
    maxOffset: 80,
    loop: true,
  },
  {
    id: 'layer-22',
    name: 'Partícula 2',
    depth: 0.8,
    position: 'center',
    offsetX: 40,
    offsetY: -25,
    size: 'xs',
    zIndex: 21,
    invertX: true,
    invertY: true,
    maxOffset: 85,
    loop: true,
  },
  {
    id: 'layer-23',
    name: 'Partícula 3',
    depth: 0.85,
    position: 'center',
    offsetX: -35,
    offsetY: 30,
    size: 'xs',
    zIndex: 22,
    invertX: true,
    invertY: true,
    maxOffset: 90,
    loop: true,
  },
  {
    id: 'layer-24',
    name: 'Partícula 4',
    depth: 0.9,
    position: 'center',
    offsetX: 35,
    offsetY: 35,
    size: 'xs',
    zIndex: 23,
    invertX: true,
    invertY: true,
    maxOffset: 95,
    loop: true,
  },

  // === CAPA MÁS FRONTAL ===
  {
    id: 'layer-25',
    name: 'Overlay Final',
    depth: 1.0,
    position: 'center',
    offsetX: 0,
    offsetY: 0,
    size: 'full',
    zIndex: 25,
    invertX: true,
    invertY: true,
    maxOffset: 100,
    loop: true,
  },
];

export default layersConfig;
